ERPrrhh/urls.py
from django.contrib import admin
from django.urls import path, include
from RRHH.views import *

urlpatterns = [
    path('admin/', admin.site.urls),
    
    path('', include("RRHH.urls") ),
    path('accounts/', include('django.contrib.auth.urls'))
]

RRHH/urls.py
# urls.py en tu aplicación
from django.urls import path
from .views import *

urlpatterns = [
   
    path('empleado/perfil/<id>', GestionarEmpleadosView, name="perfil_empleado"),
    path('empleado/permisos/<id>',GestionarPermisosView, name='gestionar_permisosEM'),
    path('administrador/organizacion/cargos', AdministrarCargoView, name="AdministrarCargoView"),
    path('administrador/pagos/nuevoPago',CrearPagoView, name="CrearPagoView"),
    path('empleado/permisos/solicitarPermiso/<id>',SolicitarPermisoView, name='solicitar_permiso'),
    path('',HomeView, name= "HomeView"),
    #ruta pantallas Eduardo
    path('administrador/Organizacion/areas',AdministrarAreaView, name="AdministrarAreaView"),
    path('administrador/Organizacion/areas/gestionarArea',GestionarAreaView),
    path('administrador/Organizacion/cargos/gestionarCargo',GestionarCargoView, name="GestionarCargoView"),
    path('administrador/permisos',GestionarPermisoADView),
    path('administrador/Organizacion',GestionarOrganizacionView,name="GestionarOrganizacionView"),
    path('administrador/pagos/modificar',ModificarPagoView, name="ModificarPagoView"),
    #Crear empleado
    path('administrador/empleado',GestionarEmpleadoADView, name='GestionarEmpleadoADView'),
    path('get_cargos/', get_cargos, name='get_cargos'),
    path('get_municipios/', get_municipios, name='get_municipios'),

    
    path('administrador/pagos',GestionarPagoADView),
    path('empleado/pagos/<id>',GestionarPagoEMView, name='mis_pagos'),
    path('EliminarCargo/<int:id>', EliminarCargo, name="EliminarCargo"),
    path('EliminarArea/<int:id>', EliminarArea, name="EliminarArea"),
    path('EliminarEmpleadp/<id>', EliminarEmpleado, name="EliminarEmpleado"),
    path('ModificarCargo/<id>', ModificarCargo, name="ModificarCargo"),
    path('ModificarArea/<id>', ModificarArea, name="ModificarArea"),
    path('registro/<id>',Registro,name="Registro"),
    path('logout/',exit,name="exit" ),
    
    path('administrador/asistencia',RegistrarAsistenciaView),
    # path('administrador/asistencias',RegistrarAsistenciaView, name="RegistrarAsistenciaView"),
    # path('administrador/asistencias/guardar', save_csv, name="save_csv"),
]

RRHH/models.py
from django.db import models

# Create your models here.
class Area(models.Model):
    "Esta es una clase que representa un área" 
    id_area = models.AutoField(primary_key=True)
    nombre_area = models.CharField(max_length=50)
    descripcion_area = models.TextField(max_length=100)
    encargado = models.OneToOneField('Empleado', blank=True, null=True, on_delete=models.SET_NULL, related_name='area_encargada')

    def __str__(self):
        return str(self.nombre_area) 

class Cargo(models.Model):
    "Esta es una clase que representa un cargo dentro de un área" 
    id_cargo = models.AutoField(primary_key=True)
    area = models.ForeignKey(Area, on_delete=models.CASCADE, related_name='cargos')
    nombre_cargo = models.CharField(max_length=50)
    descripcion_cargo = models.TextField(max_length=100)

    def __str__(self):
        return f'{self.nombre_cargo}'

class Empleado(models.Model):
    "Esta es una clase que representa un empleado"
    carnet = models.CharField(max_length=6, primary_key=True)
    nombres = models.CharField(max_length=50)
    apellidos = models.CharField(max_length=50)
    dui = models.CharField(max_length=9)
    area = models.ForeignKey(Area, on_delete=models.CASCADE, related_name='empleados_area', default=1)
    cargo = models.ForeignKey(Cargo, on_delete=models.CASCADE, related_name='empleados_cargo')  
    departamento = models.ForeignKey('Departamento', on_delete=models.CASCADE, related_name='empleados_departamento', default=1)
    municipio = models.ForeignKey('Municipio', on_delete=models.CASCADE, related_name='empleados_municipio', default=1)
    telefono = models.CharField(max_length=8, default='0000-0000')
    sexo = [
        ('M', 'Masculino'),
        ('F', 'Femenino')
        ]
    roles = [
        ('1', 'Administrador'),
        ('2', 'Empleado')
        ]
    rol = models.CharField(max_length=1, choices=roles, default='2')
    genero = models.CharField(max_length=1, choices=sexo, default='M')
    fechanacimiento = models.DateField()
    direccion = models.TextField()
    salariobase = models.DecimalField(max_digits=10, decimal_places=2)

    def __str__(self):
        return f'{self.nombres} {self.apellidos}'
    
# class auth_user(models.Model):
#     "Esta es una clase que representa un usuario del sistema"
#     id = models.AutoField(primary_key=True)
#     username = models.ForeignKey(Empleado, on_delete=models.CASCADE, related_name='usuarios')
#     password = models.TextField(max_length=256)
#     is_superuser = models.BooleanField(default=False)
#     is_staff = models.BooleanField(default=False)
#     is_active = models.BooleanField(default=True)
#     date_joined = models.DateTimeField(auto_now_add=True)

#     def __str__(self):
#         return str(self.username)

class Departamento(models.Model):
    "Esta es una clase que representa un departamento del pais El Salvador"
    id_departamento = models.AutoField(primary_key=True)
    nombre_departamento = models.TextField(max_length=50)
    def __str__(self):
        return str(self.nombre_departamento)

class Municipio(models.Model):
    "Esta es una clase que representa un municipio del pais El Salvador" 
    id_municipio = models.AutoField(primary_key=True)
    departamento = models.ForeignKey(Departamento, on_delete=models.CASCADE, related_name='municipios')
    nombre_municipio = models.TextField(max_length=50)

    def __str__(self):
        return f'{self.nombre_municipio}'

class Pago(models.Model):
    "Esta es una clase que representa un pago"
    codigo_pago = models.AutoField(primary_key=True)
    carnet = models.ForeignKey(Empleado, on_delete=models.CASCADE, related_name='pagos')
    asistencia = models.ForeignKey('Asistencia', on_delete=models.CASCADE, related_name='pagos', default=1)
    bono = models.DecimalField(max_digits=10, decimal_places=2)
    subtotal = models.DecimalField(max_digits=10, decimal_places=2)
    totalpagar = models.DecimalField(max_digits=10, decimal_places=2)
    isss = models.DecimalField(max_digits=10, decimal_places=2)
    afp = models.DecimalField(max_digits=10, decimal_places=2)
    renta = models.DecimalField(max_digits=10, decimal_places=2)
    fechapago = models.DateField()

    def __str__(self):
        return f'Pago {self.codigo_pago} - {self.carnet}'

class Asistencia(models.Model):
    "Esta es una clase que representa la asistencia de un empleado"
    id_asistencia = models.AutoField(primary_key=True)
    carnet = models.ForeignKey(Empleado, on_delete=models.CASCADE, related_name='asistencias')
    horas_trabajadas_diunas = models.IntegerField(default=0)
    horas_trabajadas_nocturnas = models.IntegerField(default=0)
    horas_extras_diurnas = models.IntegerField(default=0)
    horas_extras_nocturnas = models.IntegerField(default=0) 
    mes = [
        ('1', 'Enero'),
        ('2', 'Febrero'),
        ('3', 'Marzo'),
        ('4', 'Abril'),
        ('5', 'Mayo'),
        ('6', 'Junio'),
        ('7', 'Julio'),
        ('8', 'Agosto'),
        ('9', 'Septiembre'),
        ('10', 'Octubre'),
        ('11', 'Noviembre'),
        ('12', 'Diciembre'),
        ]
    mes_asistencia = models.CharField(max_length=2, choices=mes, default='1')

    def __str__(self):
        return f'Asistencia {self.id_asistencia} - {self.carnet}'

class Permiso(models.Model):
    "Esta es una clase que representa un permiso de un empleado"
    codigo_permiso = models.AutoField(primary_key=True)
    carnet = models.ForeignKey(Empleado, on_delete=models.CASCADE, related_name='permisos')
    fechainicio = models.DateField()
    fechafinal = models.DateField()
    justificacion = models.TextField()
    estado = [
        ('1', 'Aprobado'),
        ('2', 'Rechazado'),
        ('3', 'Pendiente'),
        ]
    estado = models.TextField(max_length=10, choices=estado, default='Pendiente')

    def __str__(self):
        return f'Permiso {self.codigo_permiso} - {self.carnet}'

RRHH/templates/ADadministrarArea.html
<!DOCTYPE html>
<html lang="es">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Administrar áreas</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.3/font/bootstrap-icons.min.css">
    <style>
      html, body {
           height: 100%;
           margin: 0;
       }
       .centrado {
           display: flex;
           justify-content: center; /* Centra horizontalmente */
               /* Centra verticalmente */
       }
       nav{
       display: flex;
       align-items: center;
       justify-content: space-between;
       padding-top: 20px;
       padding-left: 5%;
       padding-right: 5%;
       font-weight: bold;
       background-color: #0085fc;
   }
   h1{
       color: white;
       font-size: 30px;
   }
   
   ul li{
       display: inline-block;
       padding: 0px 20px;
       font-size: 20px;
   }
   a{
       color: white;
       text-decoration: none;
   }
   .desplazar{
       padding-left: 120px;
       margin-right: 20px;
   }
   .table {
            width: 100%;
            border-collapse: collapse;
            margin-top: 2%;
        }
        .table th,.table td {
            border: 1px solid #ddd;
            padding: 8px;
            text-align: center;
        }
        #espcio{
            margin-right: 80px;
            
        }
   </style>
</head>
<body >
    {% extends 'navCard.html' %}
    {% block content %}
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>
    
      <!-- <header>
        <nav>
            <h1>RRHH</h1>
            <ul>
                <li><a href="#">Inicio</a></li>
                <li><a href="/administrador/Organizacion">Organización</a></li>
                <li><a href="/administrador/permisos">Permisos</a></li>
                <li><a href="/administrador/pagos">Pagos</a></li>
                <li><a href="/administrador/asistencia">Asistencia</a></li>
            </ul>
        </nav>
    </header> -->
    <br><br>
    <div class="container ">
        <h2 class="text-center mb-4">Administrar Área</h2>

        <div>
            <a class="btn btn-secondary" role="button" href="/rrhh/administrador/Organizacion/areas/gestionarArea">Nueva Área</a>
            
        </div>
        
        <table class="table">
            <thead>
                <tr>
                    <th>Codigo</th>
                    <th>Nombre</th>
                    <th>Descripcion</th>
                    <th>Acciones</th>
                </tr>
            </thead>
            <tbody>
                {% for area in areas %}

                <tr>
                    <td>{{area.id_area}}</td>
                    <td>{{area.nombre_area}}</td>
                    <td>{{area.descripcion_area}}</td>
                    <td>
                        {% if area.id_area %}
                        <a class="btn" role="button" href="{% url 'ModificarArea' area.id_area %}" style="background-color: white;">
                            <svg xmlns="http://www.w3.org/2000/svg" width="25" height="25" fill="currentColor" class="bi bi-pencil" viewBox="0 0 16 16">
                                <path d="M12.146.146a.5.5 0 0 1 .708 0l3 3a.5.5 0 0 1 0 .708l-10 10a.5.5 0 0 1-.168.11l-5 2a.5.5 0 0 1-.65-.65l2-5a.5.5 0 0 1 .11-.168zM11.207 2.5 13.5 4.793 14.793 3.5 12.5 1.207zm1.586 3L10.5 3.207 4 9.707V10h.5a.5.5 0 0 1 .5.5v.5h.5a.5.5 0 0 1 .5.5v.5h.293zm-9.761 5.175-.106.106-1.528 3.821 3.821-1.528.106-.106A.5.5 0 0 1 5 12.5V12h-.5a.5.5 0 0 1-.5-.5V11h-.5a.5.5 0 0 1-.468-.325"/>
                            </svg>
                        {% endif %}
                        {% if area.id_area %}
                        <a class="btn" role="button" href="{% url 'EliminarArea' area.id_area %}" style="background-color: white;">
                            <svg xmlns="http://www.w3.org/2000/svg" width="25" height="25" fill="currentColor" class="bi bi-trash" viewBox="0 0 16 16">
                                <path d="M5.5 5.5A.5.5 0 0 1 6 6v6a.5.5 0 0 1-1 0V6a.5.5 0 0 1 .5-.5m2.5 0a.5.5 0 0 1 .5.5v6a.5.5 0 0 1-1 0V6a.5.5 0 0 1 .5-.5m3 .5a.5.5 0 0 0-1 0v6a.5.5 0 0 0 1 0z"/>
                                <path d="M14.5 3a1 1 0 0 1-1 1H13v9a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2V4h-.5a1 1 0 0 1-1-1V2a1 1 0 0 1 1-1H6a1 1 0 0 1 1-1h2a1 1 0 0 1 1 1h3.5a1 1 0 0 1 1 1zM4.118 4 4 4.059V13a1 1 0 0 0 1 1h6a1 1 0 0 0 1-1V4.059L11.882 4zM2.5 3h11V2h-11z"/>
                            </svg>
                         </a>
                         {% endif %}
                </td>
                {% endfor %}
            </tbody>
        </table>
        
    </div>
    {% endblock %}
</body>
</html>

RRHH/templates/ADgestionarArea.html

{% load crispy_forms_tags %}
<!DOCTYPE html>
<html lang="es">
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <title>Gestionar Área</title>
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
        <style>
          html, body {
              height: 100%;
              margin: 0;
          }
          .centrado {
              display: flex;
              justify-content: center; /* Centra horizontalmente */
                  /* Centra verticalmente */
          }
          nav{
          display: flex;
          align-items: center;
          justify-content: space-between;
          padding-top: 20px;
          padding-left: 5%;
          padding-right: 5%;
          font-weight: bold;
          background-color: #0085fc;
          }
          h1{
              color: white;
              font-size: 30px;
          }
          h2{
                
                font-size: 30px;
                text-align: center;
                margin-top:5%;
          }
          ul li{
              display: inline-block;
              padding: 0px 20px;
              font-size: 20px;
          }
          a{
              color: white;
              text-decoration: none;
          }
          .desplazar{
              padding-left: 120px;
              margin-right: 20px;
      }
      </style>
    </head>
    <body >
    
        
        <div>
          <header>
            <nav>
                <h1>RRHH</h1>
                <ul>
                    <li><a href="{% url 'HomeView' %}">Inicio</a></li>
    
                    {% if user.is_authenticated %}
                        {% if perms.RRHH.view_empleado %}
                    <li>
                        <a href="{% url 'perfil_empleado' user.username %}">Perfil</a>
                    </li>
                        {% endif %}
                    {% endif %}
    
                    {% if perms.RRHH.add_empleado %}
                    <li>
                        <a href="/rrhh/administrador/Organizacion">Organizacion</a>
                    </li>
                    {% endif %}
    
                    {% if user.is_authenticated %}
                        {% if perms.RRHH.view_permiso %}
                    <li>
                        <a href="{% url 'gestionar_permisosEM' user.username %}">Permisos</a>
                    </li>
                        {% endif %}
                    {% endif %}
    
                    {% if perms.RRHH.change_permiso %}
                    <li>
                        <a href="/rrhh/administrador/permisos">Permisos</a>
                    </li>
                    {% endif %}
    
                    {% if user.is_authenticated %}
                        {% if perms.RRHH.view_pago %}
                    <li>
                        <a href="{% url 'mis_pagos' user.username %}">Pagos</a>
                    </li>
                        {% endif %}
                    {% endif %}
    
                    {% if perms.RRHH.add_pago %}
                    <li>
                        <a href="/rrhh/administrador/pagos">Pagos</a>
                    </li>
                    {% endif %}
    
                    {% if perms.RRHH.add_asistencia %}
                    <li>
                        <a href="{% url 'RegistrarAsistenciaView' %}">Asistencia</a>
                    </li>
                    {% endif %}
    
                    {% if user.is_authenticated %}
                    <li>
                        <a href="{% url 'exit' %}">Logout</a>
                    </li>
                    {% endif %}
                </ul>
            </nav>
        </header>
        <div class="container">   
          <h2>Datos de Área</h2> 
            <div class="row">
              <div class="col-12 col-md-6 offset-md-3">   
                <form action="" enctype="multipart/form-data" method="post">
                  {% csrf_token %}

                  
                  {{form | crispy}}
                  
                    <!-- <div class="form-group">
                      <label for="exampleFormControlInput1">Nombre</label>
                      <input type="text" class="form-control" id="nombreAreatxt" >
                    </div>
                    <div class="form-group">
                      <label for="exampleFormControlSelect1">Responsable</label>
                      <select class="form-control" id="selectResponsable">
                        <option value="">Seleccione...</option>
                      </select>
                    </div>
                    
                    <div class="form-group">
                      <label for="exampleFormControlTextarea1">Descripción</label>
                      <textarea class="form-control" id="textoDescripcionArea" rows="3"></textarea>
                    </div> -->
                    <div class="form-actions" style="margin-top: 2%; text-align: center;">
                        <button class="btn btn-success" type="submit">Guardar</button>
                        <button class="btn btn-danger" type="button">Cancelar</button>
                    </div>
                  </form>
            
        </div>
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>
      
    </body>
</html>

RRHH/templates/EMsolicitarPermiso.html
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Solicitar permiso</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
    <style>
       html, body {
            height: 100%;
            margin: 0;
        }
        .centrado {
            display: flex;
            justify-content: center;
            align-items: center;
            height: 100% /* Centra horizontalmente */
                /* Centra verticalmente */
        }
        nav{
        display: flex;
        align-items: center;
        justify-content: space-between;
        padding-top: 20px;
        padding-left: 5%;
        padding-right: 5%;
        font-weight: bold;
        background-color: #0085fc;
    }
    h1{
        color: white;
        font-size: 30px;
    }
    ul li{
        display: inline-block;
        padding: 0px 20px;
        font-size: 20px;
    }
    a{
        color: white;
        text-decoration: none;
    }
    .desplazar{
        padding-left: 120px;
        margin-right: 20px;
    }
    </style>
</head>
  <body>
    {% extends 'navCard.html' %}
    {% block content %}
    <div class="container text-center ">
        <br><br><br><br>
        <div class="row">
            <div class="col-12 col-md-6 offset-md-3">
                <h2>Solicitar permiso</h2>
                <form method="post" action="{% url 'solicitar_permiso' user.username %}">
                    {% csrf_token %}
                    <div class="mb-3">
                        <label for="fecha-inicio" class="form-label">Fecha de inicio</label>
                        <input type="date" class="form-control" id="fecha-inicio" name="fecha_inicio" required>
                    </div>
                    <div class="mb-3">
                        <label for="fecha-fin" class="form-label">Fecha de fin</label>
                        <input type="date" class="form-control" id="fecha-fin" name="fecha_fin" required>
                    </div>
                    <div class="mb-3">
                        <label for="razon" class="form-label">Razón de la solicitud</label>
                        <textarea class="form-control" id="razon" name="razon" rows="3" required></textarea>
                    </div>
                    {% if perms.RRHH.add_permiso %}
                    <button type="submit" class="btn btn-success">Solicitar permiso</button>
                    {% endif %}
                    <button type="reset" class="btn btn-danger">Cancelar</button>
                </form>
            </div>
        </div>
      </div>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.8/dist/umd/popper.min.js" integrity="sha384-I7E8VVD/ismYTF4hNIPjVp/Zjvgyol6VFvRkX/vR+Vc4jQkC+hVqc2pM8ODewa9r" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.min.js" integrity="sha384-0pUGZvbkm6XF6gxjEnlmuGrJXVbNuzT9qBBavbLwCsOGabYfZo0T0to5eqruptLy" crossorigin="anonymous"></script>
    {% endblock %}
    </body>
</html>

RRHH/templates/navCard.html

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title></title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.3/font/bootstrap-icons.min.css">
    <style>
        html,body{
            margin: 0;
        }
        nav{
        display: flex;
        align-items: center;
        justify-content: space-between;
        padding-top: 20px;
        padding-left: 5%;
        padding-right: 5%;
        font-weight: bold;
        background-color: #0085fc;
    }
    h1{
        color: white;
        font-size: 30px;
    }
    ul li{
        display: inline-block;
        padding: 0px 20px;
        font-size: 20px;
    }
    a{
        color: white;
        text-decoration: none;
    }
    </style>
</head>
<body>
    <header>
        <nav>
            <h1>RRHH</h1>
            <ul>
                <li><a href="{% url 'HomeView' %}">Inicio</a></li>

                {% if user.is_authenticated %}
                    {% if perms.RRHH.view_empleado %}
                <li>
                    <a href="{% url 'perfil_empleado' user.username %}">Perfil</a>
                </li>
                    {% endif %}
                {% endif %}

                {% if perms.RRHH.add_empleado %}
                <li>
                    <a href="/rrhh/administrador/Organizacion">Organizacion</a>
                </li>
                {% endif %}

                {% if user.is_authenticated %}
                    {% if perms.RRHH.view_permiso %}
                <li>
                    <a href="{% url 'gestionar_permisosEM' user.username %}">Permisos</a>
                </li>
                    {% endif %}
                {% endif %}

                {% if user.is_authenticated %}
                {% if perms.RRHH.view_permiso %}
                <li>
                    <a href="{% url 'solicitar_permiso' user.username %}">Nuevo permiso</a>
                </li>
                    {% endif %}
                {% endif %}

                {% if perms.RRHH.change_permiso %}
                <li>
                    <a href="/rrhh/administrador/permisos">Permisos</a>
                </li>
                {% endif %}

                {% if user.is_authenticated %}
                    {% if perms.RRHH.view_pago %}
                <li>
                    <a href="{% url 'mis_pagos' user.username %}">Pagos</a>
                </li>
                    {% endif %}
                {% endif %}

                {% if perms.RRHH.add_pago %}
                <li>
                    <a href="/rrhh/administrador/pagos">Pagos</a>
                </li>
                {% endif %}

                {% if perms.RRHH.add_asistencia %}
                <li>
                    <a href="{% url 'RegistrarAsistenciaView' %}">Asistencia</a>
                </li>
                {% endif %}

                {% if user.is_authenticated %}
                <li>
                    <a href="{% url 'exit' %}">Logout</a>
                </li>
                {% endif %}
            </ul>
        </nav>
    </header>
    {% block content %}
    {% endblock %}
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js"></script>
</body>
</html>